### PR TITLE
Release `v3.6.5`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `v3.6.5` release.
Here you can find all related translations changes: [v3.6.4...master](https://github.com/flarum-lang/japanese/compare/v3.6.4...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## v3.6.5

**更新内容**:

* Flarum coreの翻訳を更新.

**拡張機能の翻訳を更新**:

* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/mentions`](https://github.com/flarum/mentions)

全ての更新内容:[v3.6.4...v3.6.5](https://github.com/flarum-lang/japanese/compare/v3.6.4...v3.6.5).

</details>

### CODE REVIEW

**Review by takumi9942 — APPROVED** [review]

**Comment by takumi9942** [comment]
@rob006
Could you check this PR? This PR hasn't been merged even though I approve it.

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## バージョン [`v3.6.5`](https://github.com/flarum-lang/japanese/releases/tag/v3.6.5)

**更新内容**:

* Flarum coreの翻訳を更新.


**拡張機能の翻訳を更新**:

* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/mentions`](https://github.com/flarum/mentions)


全ての更新内容:[v3.6.4...v3.6.5](https://github.com/flarum-lang/japanese/compare/v3.6.4...v3.6.5).

更新するには以下のコマンドを実行してください:

```console
composer update flarum-lang/japanese
php flarum cache:clear
```

~~~

**Comment by rob006** [comment]
I'm not sure what happened. I ran the merge job manually and it works fine. Please don't hesitate to report this in the future - merging a PR should only take a few minutes at most. If it takes longer, it means something went wrong and there is no point in waiting any longer. After 2 months, I don't even have logs to check what happened in this case.

**Comment by takumi9942** [comment]
Thank you very much!

> merging a PR should only take a few minutes at most. If it takes longer, it means something went wrong and there is no point in waiting any longer.

Got it! I'll report asap if the same problem happens :)

**Pull request merged**
